[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
arbitrum = "${ARBITRUM_MAINNET_RPC}"

[etherscan]
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}" }

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
via_ir = true
ffi = false
fuzz_runs = 0
invocations = 0
